version: "3"
services:
  postgres:
    image: postgres:11.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: --data-checksums
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./gnorm.sql:/docker-entrypoint-initdb.d/gnorm.sql

volumes:
  postgres-data:
