# ConnStr is the connection string for the database.  Any environment variables
# in this string will be expanded, so for example dbname=$MY_DDB will do the
# right thing.
# MySQL example:
# ConnStr = "root:admin@tcp/"
# Postgres example:
ConnStr = "dbname=postgres host=127.0.0.1 sslmode=disable user=postgres password=password"

DBType = "postgres"

Schemas = ["public"]

# TODO: add linting
PostRun = ["../scripts/post-process.sh", "objection", "$GNORMFILE"]

NameConversion = "{{camel .}}"

# This will output the files in a subdirectory called "gnorm".  You can change
# this, but if you do, change the RootPkg definition below to match what the
# package name should be.
OutputDir = "./generated"

ExcludeTables = ["knex_migrations", "knex_migrations_lock"]

# PluginDirs = ["./templates/plugin"]

[Params]
# RootPkg is the package declaration for the output dir. It should match the

[SchemaPaths]
"{{toLower .Schema}}/index.ts" = "templates/table_index.gotmpl"
"{{toLower .Schema}}/extend/index.ts" = "templates/table_stub_index.gotmpl"
"{{toLower .Schema}}/enums/index.ts" = "templates/enum_index.gotmpl"

[TablePaths]
"{{toLower .Schema}}/extend/{{pascal .Table}}.ts" = "templates/table.gotmpl"
"{{toLower .Schema}}/{{pascal .Table}}.ts" = "templates/table_stub.gotmpl"

[EnumPaths]
"{{toLower .Schema}}/enums/{{pascal .Enum}}.ts" = "templates/enum.gotmpl"

[TypeMap]
"timestamp with time zone" = "Date"
"timestamptz" = "Date"
"varchar" = "string"
"text" = "string"
"boolean" = "boolean"
"uuid" = "string"
"character varying" = "string"
"character" = "string"
"smallint" = "number"
"integer" = "number"
"int4" = "number"
"int8" = "number"
"numeric" = "number"
"bigint" = "???"
# TODO
"hstore" = "any"
# TODO
"jsonb" = "any"
# TODO
"bytea" = "any"
# TODO: real column
"tstzrange" = "string"
# Replace with your own enums
"book_type" = "enums.BookType"

[NullableTypeMap]
"timestamp with time zone" = "Date | null"
"timestamptz" = "Date | null"
"varchar" = "string | null"
"text" = "string | null"
"boolean" = "boolean | null"
"uuid" = "string | null"
"character varying" = "string | null"
"character" = "string | null"
"smallint" = "number | null"
"integer" = "number | null"
"int4" = "number | null"
"int8" = "number | null"
"numeric" = "number | null"
"bigint" = "???"
# TODO
"hstore" = "any"
# TODO
"jsonb" = "any"
# TODO
"bytea" = "any"
# TODO: real column
"tstzrange" = "string"